# Generated by Django 4.2.2 on 2023-06-27 18:52

import billingApp1.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=billingApp1.models.MenuItem.imagePath)),
                ('price', models.CharField(max_length=10)),
                ('discount', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Card', 'Card'), ('UPI Payment', 'UPI Payment')], default='Cash On Delivery', max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('order_type', models.CharField(choices=[('Take Away', 'Take Away'), ('In House', 'In House')], default='In House', max_length=20)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNumber', models.CharField(max_length=3)),
                ('tableStatus', models.CharField(choices=[('ORDER', 'ORDER'), ('NO ORDER', 'NO ORDER')], default='NO ORDER', max_length=10)),
                ('totalOrder', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp1.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp1.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tabelNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billingApp1.table'),
        ),
    ]
